#!/bin/bash
# Generate session summaries for handoff
# Usage: session-summary.sh [session-name] [repo-path]

set -e

SESSION_NAME="${1:-$(basename "$(pwd)")}"
REPO_PATH="${2:-$(pwd)}"
MEMORY_DIR="${CLAUDE_MEMORY_DIR:-$HOME/.claude/memory}"
SESSIONS_DIR="$MEMORY_DIR/sessions"
OUTPUT_FILE="$SESSIONS_DIR/${SESSION_NAME}-$(date +%Y%m%d-%H%M%S).md"

# Initialize directories
init_dirs() {
    mkdir -p "$SESSIONS_DIR"
}

# Get git log for the session (commits from today by default)
get_git_log() {
    local repo="$1"
    if [ -d "$repo/.git" ] || git -C "$repo" rev-parse --git-dir > /dev/null 2>&1; then
        cd "$repo"
        # Get commits from the last 24 hours
        git log --since="24 hours ago" --oneline --no-decorate 2>/dev/null || echo "No recent commits"
    else
        echo "Not a git repository"
    fi
}

# Get files changed recently
get_files_changed() {
    local repo="$1"
    if [ -d "$repo/.git" ] || git -C "$repo" rev-parse --git-dir > /dev/null 2>&1; then
        cd "$repo"
        # Get files changed in last 24 hours
        git diff --name-only HEAD~10 2>/dev/null | head -20 || git status --short 2>/dev/null | head -20
    else
        echo "Unable to determine changed files"
    fi
}

# Get current branch
get_branch() {
    local repo="$1"
    if [ -d "$repo/.git" ] || git -C "$repo" rev-parse --git-dir > /dev/null 2>&1; then
        cd "$repo"
        git branch --show-current 2>/dev/null || echo "unknown"
    else
        echo "unknown"
    fi
}

# Generate the summary
generate_summary() {
    local session="$1"
    local repo="$2"

    init_dirs

    local date_str
    date_str=$(date "+%Y-%m-%d %H:%M")
    local branch
    branch=$(get_branch "$repo")
    local git_log
    git_log=$(get_git_log "$repo")
    local files_changed
    files_changed=$(get_files_changed "$repo")

    cat > "$OUTPUT_FILE" << EOF
# Session Summary: $session

> Date: $date_str
> Branch: $branch
> Repository: $repo

## Work Completed

### Commits Made
\`\`\`
$git_log
\`\`\`

### Files Changed
\`\`\`
$files_changed
\`\`\`

### Key Accomplishments
- [ ] TODO: Fill in accomplishments

## Pending Items

- [ ] TODO: List pending items

## Notes for Next Session

TODO: Add notes for context handoff

## Context to Remember

- Current branch: $branch
- Working directory: $repo

---

*Generated by session-summary.sh on $date_str*
EOF

    echo "Session summary written to: $OUTPUT_FILE"
}

# View recent summaries
list_summaries() {
    init_dirs
    echo "Recent session summaries:"
    ls -lt "$SESSIONS_DIR"/*.md 2>/dev/null | head -10 || echo "No summaries found"
}

# Read a specific summary
read_summary() {
    local name="$1"
    init_dirs

    if [ -z "$name" ]; then
        # Show most recent
        local latest
        latest=$(ls -t "$SESSIONS_DIR"/*.md 2>/dev/null | head -1)
        if [ -n "$latest" ]; then
            cat "$latest"
        else
            echo "No summaries found"
        fi
    else
        # Find matching summary
        local match
        match=$(ls -t "$SESSIONS_DIR"/*"$name"*.md 2>/dev/null | head -1)
        if [ -n "$match" ]; then
            cat "$match"
        else
            echo "No summary found matching: $name"
        fi
    fi
}

show_help() {
    echo "Session Summary - Generate and manage session handoff summaries"
    echo ""
    echo "Usage: session-summary.sh [command] [args...]"
    echo ""
    echo "Commands:"
    echo "  generate [name] [path]  - Generate new summary (default)"
    echo "  list                    - List recent summaries"
    echo "  read [name]             - Read a summary (latest if no name)"
    echo ""
    echo "Examples:"
    echo "  session-summary.sh                    # Generate for current directory"
    echo "  session-summary.sh generate mywork .  # Generate with custom name"
    echo "  session-summary.sh list               # List all summaries"
    echo "  session-summary.sh read mywork        # Read a specific summary"
    echo ""
    echo "Environment:"
    echo "  CLAUDE_MEMORY_DIR - Override memory directory (default: ~/.claude/memory)"
}

case "$1" in
    generate) generate_summary "${2:-$SESSION_NAME}" "${3:-$REPO_PATH}" ;;
    list) list_summaries ;;
    read) read_summary "$2" ;;
    -h|--help|help) show_help ;;
    "") generate_summary "$SESSION_NAME" "$REPO_PATH" ;;
    *)
        # If first arg doesn't match a command, treat it as session name
        if [[ "$1" != -* ]]; then
            generate_summary "$1" "${2:-$REPO_PATH}"
        else
            show_help
            exit 1
        fi
        ;;
esac
